### ISSUE TITLE
Watches hose it up

### ISSUE THREAD

**Issue by amcdnl** [goto-bus-stop/gulp-babel-external-helpers#1]
So when I kick off a watch, it runs it and builds it perfect. But when I change a file it messes up.

So given:

```
gulp.task('es6', function() {
  return gulp.src(paths.source, {base: 'src'})
    .pipe(changed(paths.output, {extension: '.js'}))
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(babel())
    .pipe(ngAnnotate())
    .pipe(babelHelpers('babelHelpers.js'))
    .pipe(sourcemaps.write('/sourcemaps', {sourceRoot: '/src'}))
    .pipe(gulp.dest(paths.output));
});
```

and the following watch task:

```
gulp.task('watch', ['es6'], function() {
  gulp.watch([paths.source], {interval: 500}, ['es6', browserSync.reload]).on('change', changed);
});
```

You can work around it by doing a separate task for watch but its kinda messy, so like:

```
gulp.task('es6:watch', function() {
  return gulp.src(paths.source, {base: 'src'})
    .pipe(changed(paths.output, {extension: '.js'}))
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(babel())
    .pipe(ngAnnotate())
    .pipe(sourcemaps.write('/sourcemaps', {sourceRoot: '/src'}))
    .pipe(gulp.dest(paths.output));
});
```

and

```
gulp.task('watch', ['es6'], function() {
  gulp.watch([paths.source], {interval: 500}, ['es6:watch', browserSync.reload]).on('change', changed);
});
```

Just wanted to see if you had any better ideas.

**Comment by goto-bus-stop** [comment]
I'm not sure that `gulp-babel-external-helpers` works with a plugin like `gulp-changed` at all, since it'll only know about the external helpers that were used in the changed files, and thus only include those. Note that you have to pass the `externalHelpers` option to `gulp-babel` to make the compiled files use the `babelHelpers` variable: without the option, it'll include the helpers in every file anyway, and the extra file that's added by `gulp-babel-external-helpers` will not be used.

I think a `watch` task _without_ the `gulp-changed` plugin should work just fine, but I can't promise that because I haven't tried! :)

Personally, I've used the separate task that you came up with too. However if the difference between your production build and dev server (maybe there's minification involved, for example) is very small, a plugin like [`gulp-if`](https://npmjs.com/gulp-if) might be a good solution.

``` js
var gulpif = require('gulp-if')
function build(useExternalHelpers) {
  return gulp.src([ paths.source ])
    .pipe(babel({ externalHelpers: !!useExternalHelpers }))
    .pipe(gulpif(useExternalHelpers, babelHelpers('babelHelpers.js')))
    .pipe(gulp.dest(paths.output))
}
```

**Comment by goto-bus-stop** [comment]
A note in the Readme about usage (or not-usage, really) with `gulp-changed` and similar plugins might be good.

**Comment by amcdnl** [comment]
Ya, like I mentioned it works fine if I only do it the first time. But that could be a odd negative side effect if I put in something that I need but wasn't in the proj ever before. Ya, its def worth mentioning though.
